services:
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: outbuild_assessment
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - outbuild
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/outbuild_assessment
      JWT_SECRET: 6952c2ed45795f9370dd0e2c0a4ceb640b9fe09ab43e06357765e907ce619d05
    volumes:
      - .:/src
    networks:
      - outbuild
    command: npm run start
networks:
  outbuild:
    name: outbuild
