services:
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: outbuild_assessment
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - outbuild
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/src
    networks:
      - outbuild
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: npm run start
networks:
  outbuild:
    name: outbuild
